FROM node:16

ARG STRAPI_PORT

# Set environment variables
ENV APP_DIR="/usr/src/app" \
	NPM_CONFIG_LOGLEVEL="warn" \
	NODE_ENV="production" \
	NODE_OPTIONS="--max_old_space_size=8192"

WORKDIR ${APP_DIR}

COPY . .

RUN npm ci

EXPOSE ${STRAPI_PORT}

CMD ["npm", "run", "prod"]
