version: '3.9'

services:
  api:
    container_name: nodejs-app
    image: nodejs-app
    build:
      context: ../
      dockerfile: ./docker/Dockerfile-dev
    env_file: ../.env
    environment:
      NODE_ENV: development
    ports:
      - "1337:1337"
    volumes:
      - "app-data:/var/lib/strapi"
      - "../node_modules:/usr/src/app/node_modules"
      - "../.:/usr/src/app"
    restart: unless-stopped
    tty: true
    networks:
      - app-network

volumes:
  app-data:
  node_modules:


networks:
  app-network:
    driver: bridge
